name: "Set label and project of minutes"
on:
  issues:
    types: [opened, labeled]

jobs:
  set-label:
    name: Set label to meeting
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Meeting"], "labels": ["meeting"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  assign-project:
    name: Set project to meeting
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.title, 'Meeting')
        with:
          project: 'https://github.com/many-speech-analyses/many_analyses/projects/1'
          column_name: 'Next'
